# This is just a suggestion. You may add any services you find necessary here.
services:
  s3mock:
    image: adobe/s3mock:latest
    environment:
      - debug=true
      - retainFilesOnExit=true
      - root=containers3root
      - initialBuckets=cocrafter-dev
    ports:
      - 8001:9090
    volumes:
      - ./locals3root:/containers3root


  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    ports:
      - 3000:3000
    environment:
      - VITE_BACKEND_URL=http://localhost:8000


  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db
      - S3_ENDPOINT=http://s3mock:9090
    depends_on:
      - db
      - s3mock
    restart: always


  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - 8002:5432
    volumes:
     - pgdata:/var/lib/postgresql/data


  legacy-backend:
    build:
      dockerfile: Dockerfile
      context: legacy-backend
    ports:
      - 8003:8003
    expose:
      - 8003
    restart: always





volumes:
  pgdata: